name: generate documentation

on:
  push:
    branches:
      - main
  # Useful if for some reason I want to manually trigger the workflow
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install elan
        run: |
          curl https://elan.lean-lang.org/elan-init.sh -sSf | sh -s -- -y
          echo "$HOME/.elan/bin" >> $GITHUB_PATH

      - name: Get Mathlib cache
        run: lake exe cache get

      - name: Build documentation
        run: |
          lake -R -Kdoc=on build IMOSLLean4:docs

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .lake/build/doc

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
